# Generated by Django 5.1.3 on 2024-12-12 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_category_alter_debate_author_alter_debate_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participated_debates', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('side', models.CharField(choices=[('Pro', 'Pro'), ('Con', 'Con')], max_length=3, verbose_name='Side')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_arguments', to='debate.debate', verbose_name='Debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
