# Generated by Django 5.1.3 on 2024-12-12 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_debate_participants_argument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_debates', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
