# Generated by Django 5.1.3 on 2024-12-12 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_alter_debate_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
