# Generated by Django 5.1.3 on 2024-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0007_argument_winner_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Vote count'),
        ),
    ]
